# Generated by Django 4.1.4 on 2022-12-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('classification_type', models.CharField(choices=[('category', 'Category'), ('region', 'Region'), ('country', 'Country'), ('city', 'City'), ('season', 'Season')], default='category', max_length=20, verbose_name='classification type')),
                ('synonyms', models.TextField(blank=True, help_text='The clause (query) should appear in the matching documents.', verbose_name='synonyms')),
                ('antonyms', models.TextField(blank=True, help_text='The clause (query) must not appear in the matching documents.', verbose_name='antonyms')),
            ],
            options={
                'verbose_name': 'Classification',
                'verbose_name_plural': 'Classifications',
                'ordering': ('order',),
                'index_name': 'portal.documents.product',
                'mapping_template': 'mappings/portal.documents.classification.json',
            },
        ),
        migrations.CreateModel(
            name='CategoryClassification',
            fields=[
            ],
            options={
                'verbose_name': 'Category classification',
                'verbose_name_plural': 'Category classifications',
                'proxy': True,
                'index_name': 'portal.documents.product',
                'mapping_template': 'mappings/portal.documents.classification.json',
                'indexes': [],
                'constraints': [],
            },
            bases=('classifications.classification',),
        ),
        migrations.CreateModel(
            name='CityClassification',
            fields=[
            ],
            options={
                'verbose_name': 'City classification',
                'verbose_name_plural': 'City classifications',
                'proxy': True,
                'index_name': 'portal.documents.product',
                'mapping_template': 'mappings/portal.documents.classification.json',
                'indexes': [],
                'constraints': [],
            },
            bases=('classifications.classification',),
        ),
        migrations.CreateModel(
            name='CountryClassification',
            fields=[
            ],
            options={
                'verbose_name': 'Counrty classification',
                'verbose_name_plural': 'Country classifications',
                'proxy': True,
                'index_name': 'portal.documents.product',
                'mapping_template': 'mappings/portal.documents.classification.json',
                'indexes': [],
                'constraints': [],
            },
            bases=('classifications.classification',),
        ),
        migrations.CreateModel(
            name='RegionClassification',
            fields=[
            ],
            options={
                'verbose_name': 'Region classification',
                'verbose_name_plural': 'Region classifications',
                'proxy': True,
                'index_name': 'portal.documents.product',
                'mapping_template': 'mappings/portal.documents.classification.json',
                'indexes': [],
                'constraints': [],
            },
            bases=('classifications.classification',),
        ),
        migrations.CreateModel(
            name='SeasonClassification',
            fields=[
            ],
            options={
                'verbose_name': 'Season classification',
                'verbose_name_plural': 'Season classifications',
                'proxy': True,
                'index_name': 'portal.documents.product',
                'mapping_template': 'mappings/portal.documents.classification.json',
                'indexes': [],
                'constraints': [],
            },
            bases=('classifications.classification',),
        ),
    ]
