# Generated by Django 4.1 on 2022-12-13 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='classification',
            name='slug',
            field=models.SlugField(verbose_name='slug'),
        ),
        migrations.AlterUniqueTogether(
            name='classification',
            unique_together={('slug', 'name', 'classification_type')},
        ),
    ]
